### ISSUE TITLE
Include Pangeo-forge proposal?

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-forge/roadmap#2]
Could the publicly-releasable parts of the Pangeo-Forge proposal be included here? (or somewhere?)

**Comment by rabernat** [comment]
We will do this as soon as we have official approval from NSF to announce the award. This will be coupled with a blog post about pangeo forge.

Hopefully this will be within a few weeks.

**Comment by rabernat** [comment]
Better late than never. The Pangeo Forge proposal is now online here: https://figshare.com/articles/preprint/EarthCube_Data_Capabilities_A_Cloud-Native_Data_Repository_for_the_Geoscience_Community/12815843
