### ISSUE TITLE
Continuously improving our biweekly meetings 

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/roadmap#21]
We have been running biweekly meetings since August. ([Meeting notes doc](https://docs.google.com/document/d/14FpI9vaM6TeFtmM7LP9o_d5DZaYKgQVTTzT7tFRt-Nw/edit#))

IMO, these meetings have been relatively effective for coordination. But there is also room to improve their organization and structure. Below are some proposals, for which I am seeking feedback from @pangeo-forge/dev-team.

### Purpose and intended participants for the biweekly meeting

We should clearly define the purpose of the biweekly meeting. To me it seems to have two potentially competing purposes:

- To facilitate _discussion_ and make _decisions_ about complex technically issues that cannot be resolved through asynchronous github discussions.
- To _inform_ interested parties about the Pangeo Forge project. (For example, we frequently invite new people to the meeting, such as the Google folks or [upcoming] the Goddard folks.)

Given the finite length of the meeting, these two objectives are in competition: people new to the project are bored by detailed technical discussion, and seasoned collaborators are bored by high-level exposition.

The _purpose_ question is closely tied to the question of who should attend the meeting. The technical discussion is most effective with a smaller group. I am fine with an unlimited number of "observers" at the meeting, who may be there just to onboard and absorb knowledge passively. But that may not be the most effective way to onboard, and is certainly not a good way to actively entrain new volunteer contributors.

**I propose we eliminate the _inform interested parties_ objective from the bi-weekly meetings.** We can inform and onboard through other means, such as better online documentation, videos, and demos. In special cases, we can schedule one-off meetings to encourage potential new high-value collaborators.

### Moderation and notetaking

I am currently doing too much at our meetings. I always serve as moderator and often also take notes. Plus I have a lot to say as a participant. I think we should switch to a mode where we appoint a dedicated moderator for each meeting. Ideally this moderator should not be an active participant, but I don't know where we would find such a person. As a compromise, perhaps we could rotate moderator duties among @pangeo-forge/dev-team. We should also have a notetaker for each meeting.

### Agenda 

Currently I am the only one developing the meeting agenda. I would like to switch to a more collaborative mode, wherein team members add items to the agenda throughout each two-week intra-meeting period (sprint?). The agenda items should be motivated by the **meeting purpose**, as defined above. What belongs on the agenda? What is the best use of our limited face-to-face time? I believe the focus should be on issues that really benefit from back-and-forth real-time discussion. Ideally we should all review the agenda before the meeting and come prepared with our thoughts.

---

Let me know how you feel about these suggestions. They are informed by my evolving understanding of how to run an effective meeting, much of which comes from [Greg Wilson's book](https://books.google.com/books?id=7PqzDwAAQBAJ&pg=PT229&lpg=PT229&dq=greg+wilson+how+to+run+a+meeting&source=bl&ots=S8mwm3z_wE&sig=ACfU3U2XtShWFjsct2aXROxdPvAV02x0vA&hl=en&sa=X&ved=2ahUKEwi29PKHlcfwAhWkY98KHZGOA3MQ6AEwBXoECAUQAw#v=onepage&q=greg%20wilson%20how%20to%20run%20a%20meeting&f=false).

**Comment by cisaacstern** [comment]
> I propose we eliminate the inform interested parties objective from the bi-weekly meetings.

👍 
> As a compromise, perhaps we could rotate moderator duties among @pangeo-forge/dev-team. We should also have a notetaker for each meeting.

Does anyone know of a good approach to manage the Moderator and Notetaker role assignments? I note that not everyone on @pangeo-forge/dev-team can come to every meeting, so rotating through the whole list is infeasible. And even among regular attendees, bandwidth will obviously vary week-to-week. Ideally we can alleviate Ryan's burden while also:

   1. Having a transparent method for tracking, assigning, and re-assigning (as needed) weekly roles
   2. ... that does not require adding an additional site/app into the mix.
      - Is there a way to manage this through GitHub Projects, perhaps? 🤔 

> I believe the focus should be on issues that really benefit from back-and-forth real-time discussion. 

Is it too prescriptive to suggest that every item added to the Agenda be linked (literally/click-ably) to an open Issue on some pangeo-forge repo? In the best case scenario this allows meeting participants to both prep and follow-up more easily.

**Comment by ciaranevans** [comment]
> Is it too prescriptive to suggest that every item added to the Agenda be linked (literally/click-ably) to an open Issue on some pangeo-forge repo? In the best case scenario this allows meeting participants to both prep and follow-up more easily.

Fully support this, would definitely stop off-topic convos happening if we limit it to only points raised by issues

> Does anyone know of a good approach to manage the Moderator and Notetaker role assignments? I note that not everyone on @pangeo-forge/dev-team can come to every meeting, so rotating through the whole list is infeasible. And even among regular attendees, bandwidth will obviously vary week-to-week. Ideally we can alleviate Ryan's burden while also:
Having a transparent method for tracking, assigning, and re-assigning (as needed) weekly roles
... that does not require adding an additional site/app into the mix.
Is there a way to manage this through GitHub Projects, perhaps? 🤔

I think we should just take the approach that we're all adults here, we should be on the assumption that participation in the meeting means you could be the moderator/note taker (with the acknowledgement that people may have no experience in it - lets make it a safe space to learn that skill)

Adding any more processes than that just gets silly IMO. Someone will be voluntold and that should be it 🎉

**Comment by rabernat** [comment]
Reminder to add any agenda items that you think will benefit from real-time discussion to the [agenda](https://docs.google.com/document/d/14FpI9vaM6TeFtmM7LP9o_d5DZaYKgQVTTzT7tFRt-Nw/edit#)!

**Comment by rabernat** [comment]
Hi Folks! Looking forward to our meeting today. There are a few items on the agenda. Everyone should feel free to add additional items that will benefit from discussion.

**Comment by rabernat** [comment]
A heads up that **I will not be able to attend next Monday**. (We are flying to Italy that day.)

Please carry on and meet without me. Is there any volunteer to chair?

**Comment by cisaacstern** [comment]
I will be there and can chair.

All are invited to add to the [agenda](https://docs.google.com/document/d/14FpI9vaM6TeFtmM7LP9o_d5DZaYKgQVTTzT7tFRt-Nw/edit#).

Looking forward.

**Comment by rabernat** [comment]
I will be at the meeting on Monday and look forward to catching up with our progress after some time away.

@pangeo-forge/dev-team: Please don't forget to add items to the agenda before the meeting.

**Comment by rabernat** [comment]
We will be meeting today at 11am PT / 2pm ET / 8pm CET. Please add items to the [agena](https://docs.google.com/document/d/14FpI9vaM6TeFtmM7LP9o_d5DZaYKgQVTTzT7tFRt-Nw/edit#) and review prior to the meeting. Looking forward to connecting.

**Comment by rabernat** [comment]
Looking forward to the meeting today at 11am PT / 2pm ET. As usual, please review / augment agenda prior to the meeting.

**Comment by rabernat** [comment]
Hi all. There will be **no coordination meeting on Monday Oct. 11**. This is Columbus Day / Indigenous Peoples Day, a NY and Columbia school holiday.

**Comment by rabernat** [comment]
FYI, I **will be online today** for our 2pm ET meeting. I'm not sure who is back at work yet, but I will be happy to chat about Pangeo Forge and start getting the momentum going again post holidays.

**Comment by rabernat** [comment]
How do people feel about our scheduled meeting on Monday (MLK day)? It's a holiday for our son's school, so mildly inconvenient for me to meet. But I'd like to hear others' opinions. 👍  or 👎  to meeting on Monday Jan 17?

**Comment by cisaacstern** [comment]
I'm 👎 just because it's a holiday and, personally, I don't have any pressing agenda items.

**Comment by rabernat** [comment]
Hi Folks! We have an important coordination meeting today. Charles and I have gotten the REST API into a useable state. Now we need to think through how this will fit into our existing automation / orchestration framework. I'm hoping to do a whiteboard session with the group. @sharkinsspatial - do you think you'll be able to make it today?

**Comment by sharkinsspatial** [comment]
@rabernat I will be there 👍

**Comment by rabernat** [comment]
We did not meet today due to the Juneteenth holiday.

I propose we hold our bi-weekly meeting on **Wednesday, June 22 at 2pm**. I have changed the calendar to reflect this.

**Comment by rabernat** [comment]
I created a category on the Discourse forum for Pangeo Forge: https://discourse.pangeo.io/c/working-groups/pangeo-forge/62

From now on, we will post updates about the bi-weekly meetings on this thread: https://discourse.pangeo.io/t/pangeo-forge-working-group-and-coordination-meetings/2816/2

(The meeting on Oct 10 is cancelled due to the holiday.)
