### ISSUE TITLE
"Open Science in Action" Abstract for AGU Fall 2021: co-authorship invitation

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/roadmap#28]
We will be submitting an abstract about Pangeo Forge to the [Open Science in Action session](https://agu.confex.com/agu/fm21/prelim.cgi/Session/122142) of AGU Fall 2021, working title:

**Pangeo Forge: A New Integrated Platform for Analysis-Ready, Cloud Optimized Data Production**

As noted [here](https://twitter.com/ChelleGentemann/status/1420836357241409539?s=20), the deadline for submission is __*this upcoming Wednesday, August 11*__ (6 days from time of this posting). Apologies that I did not organize this sooner, but I do still believe that we have enough time to turn out a product which will bring some great attention to this work.

[Here is a Google doc](https://docs.google.com/document/d/1r6obtolyBCqIy1wVbfO2R9Naa3Qc1NJgJDY19MqbkEc/edit?usp=sharing) where I've written a first draft on which I welcome your revisions. I will incorporate any suggested changes roughly daily, and plan to finalize and submit the document on ~~__*Tuesday, August 10*__ (5 days from time of this posting)~~

> __*Edit*__: See comment below re: new deadline. 

If you participate in the document, please make sure to complete the table of information at the end, so that I know what name, email, etc. you would like me to use when adding you as a co-author on AGU. I welcome substantial revisions, but even just a typo correction or reading and giving a 👍  is also a very helpful form of participation.

> To ease the collaboration process, please make any edits by first selecting the **Suggesting** option from the editing mode dropdown menu at the top right corner of the screen, as shown here:
> <img width="282" alt="Screen Shot 2021-08-05 at 12 01 14 PM" src="https://user-images.githubusercontent.com/62192187/128406623-30f431b5-c4a4-486f-b3d9-5ff4577a9a43.png">

cc @pangeo-forge/dev-team @rwegener2

**Comment by cisaacstern** [comment]
Per [this update](https://discourse.pangeo.io/t/jupyter-pangeo-open-science-connected-sessions-at-agu-2021/1667/14), the deadline has been extended to Aug 25.

Just so we don't hit any last-minute technical issues, I will plan to submit this document on **Wednesday, August 18.**

Thanks to all who've contributed thus far, and to those who haven't, there's still a week left!

**Comment by cisaacstern** [comment]
I've just submitted this abstract to AGU. The final text is reflected in the google doc. Thanks to all for your input. Everyone who contributed should receive a confirmation email from AGU.

If you expected to be a co-author and do *not* receive the AGU notification, please email me (address on page 2 of the google doc) and I'll sort it out!

**Comment by cisaacstern** [comment]
I've published a poster for this session: https://agu2021fallmeeting-agu.ipostersessions.com/default.aspx?s=20-98-4D-18-67-46-BA-D7-07-09-07-14-94-06-FF-B5&guestview=true

These posters can be edited at anytime between now and the presentation date (Fri Dec 17), so feel free to let me know of any suggested changes.

**Comment by jbusecke** [comment]
This looks very nice! I wonder if it might be worth shrinking/stretching the figures (at least the upper right), so they are immediately visible without having to click?

**Comment by cisaacstern** [comment]
> so they are immediately visible

I actually tried to do this initially and was thwarted by the iPoster interface. Couldn't figure out how to do this 😅

**Comment by jbusecke** [comment]
Oh nooo
