### ISSUE TITLE
regular coordination meetings

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/roadmap#3]
I'm noticing a lot of interest and enthusiasm around pangeo forge. I think it would be useful to start regular project meetings. I propose we do these bi-weekly. Give a 👍  if you'd be interested in attending such a meeting.

In keeping with my [new policy](https://medium.com/@rabernat/advising-and-collaborating-during-a-pandemic-and-sabbatical-ca9531b82b6d) I would prefer to meet on Monday or Friday. Monday afternoon is currently relatively open for me.

**Comment by jhamman** [comment]
Big +1 here. I'm generally free on Mondays (after 2p ET) and Fridays (after 12p ET).

cc'ing a few people that may be interested: @abarciauskas-bgse, @scottyhq, @rsignell-usg, @dgergel, @tjcrone, @jbusecke, @davidbrochart, @martindurant, @ocefpaf.

**Comment by tjcrone** [comment]
Double-plus one over here. Either afternoon works for me!

cc: @rsignell-usgs

**Comment by jbusecke** [comment]
Super keen on joining these. Could probably join starting Aug 31st (currently on vacation).

**Comment by abarciauskas-bgse** [comment]
Thanks for tagging @jhamman - Building from Joe's availability: I'm free every Monday at 2pm, 3pm and every other Monday starting August 24th at 5pm. Also usually free Fridays after 12pm ET.

**Comment by rsignell-usgs** [comment]
Monday afternoons after 2pm ET are good for me too!

**Comment by martindurant** [comment]
Thanks for the ping. I can also do Mondays.

**Comment by rabernat** [comment]
Ok great to see the enthusiasm!

I propose that we hold our first meeting on Monday, Aug. 24, at 2pm ET. From there we can establish a meeting frequency.

**Comment by rabernat** [comment]
Thanks to @jhamman, the meeting has been added to the Pangeo calendar, visible at http://pangeo.io/meeting-notes.html.

**Comment by dgergel** [comment]
@jhamman thanks for the ping and @rabernat thanks for pushing this forward. Monday works for me as well.

**Comment by rabernat** [comment]
Also pinging @charlesbluca and @naomi-henderson. I hope you can both join the meeting to get up to speed on where pangeo forge is heading.

**Comment by charlesbluca** [comment]
That time works for me - looking forward to the meeting!

**Comment by rabernat** [comment]
The meeting is full at 12 people. Let me know here if anyone else is trying to get in.

**Comment by jhamman** [comment]
Reminder, we'll be having our _now_ bi-weekly Pangeo-Forge call today at 2pm ET... https://whereby.com/pangeo

**Comment by rabernat** [comment]
I'm sorry but due to a pre-existing conflict, I won't be able to make the meeting today. I trust you will all carry on without me.

**Comment by rabernat** [comment]
Reminder that there will be a meeting today at 2pm EDT. I will chair. https://whereby.com/pangeo

Unless people have other agenda items, I'd like to use this hour to sprint on https://github.com/pangeo-forge/noaa-oisst-avhrr-feedstock/issues/1

**Comment by TomAugspurger** [comment]
I'll be there, happy to assist on
https://github.com/pangeo-forge/noaa-oisst-avhrr-feedstock/issues/1.

**Comment by TomAugspurger** [comment]
I believe we have a meeting today at 2 Eastern (10 minutes from now): whereby.com/pangeo.

With the updates from https://github.com/pangeo-forge/pangeo-forge/issues/22 in place (which I can walk through if people are interested) I think we're ready to work on a few more real pipelines before stopping to generalize again.

**Comment by rabernat** [comment]
I'll be there, perhaps a few minutes late.

**Comment by rabernat** [comment]
Just a note that I did a lot of work on Pangeo Forge last week (see https://github.com/pangeo-forge/pangeo-forge/pull/27) and am looking forward to sharing an update about this at our meeting tomorrow at 2pm EST.

**Comment by tjcrone** [comment]
This rewrite looks really cool @rabernat! I have meetings with students tomorrow as we are finishing up the last week of class and final presentations, so I will miss the meeting. I look forward to plugging in during the following weeks as the semester winds down and I can begin to refocus on Pangeo Forge. Cheers.

**Comment by TomAugspurger** [comment]
I'll be joining a bit late.

**Comment by abarciauskas-bgse** [comment]
@rabernat Is this meeting happening today?

**Comment by rabernat** [comment]
Meeting is definitely on for today! I'll be there and eager to chat about some technical details.

We could also discuss @TomAugspurger's recent [Discourse post](https://discourse.pangeo.io/t/netcdf-to-zarr-best-practices/1119).

**Comment by TomAugspurger** [comment]
I should be able to attend, but may have to step out for a bit during the hour.

**Comment by rabernat** [comment]
There will be NO MEETING TOMORROW (Jan. 4). Our first meeting of the new year will be Jan. 18.

**Comment by abarciauskas-bgse** [comment]
@rabernat just double checking we're still having the regular coordination meeting given Monday Jan 18 is MLK day and a lot of US based folks may not be working.

**Comment by rabernat** [comment]
Ah good point, I hadn't realized that.

Let's make this meeting totally optional. I'll be working that day and anyone who wants to chat with me about Pangeo Forge is welcome. But no expectations that folks will join.

**Comment by rabernat** [comment]
Just a reminder of the meeting today at 2pm ET. This will be an important one for anyone interested in contributing to the code base (see #8 for project boards).

I've also created the @pangeo-forge/dev-team group. Please let me know if you want to be added to that.

**Comment by ciaranevans** [comment]
Could I be added to the group @rabernat ? Cheers

**Comment by andersy005** [comment]
> I've also created the @pangeo-forge/dev-team group. Please let me know if you want to be added to that.

Could I be added too?

**Comment by rabernat** [comment]
The bi-weekly meeting scheduled for today falls on a federal holiday. I'll still show up (kid is in school == I am at work), but everyone should consider this meeting 100% optional. If you want to swing by and chat Pangeo Forge, you are welcome.

**Comment by abarciauskas-bgse** [comment]
@rabernat just fyi I have a conflict for the recurring meeting today but I believe @sharkinsspatial and @ciaranevans will be there with an update on pangeo-forge-aws-bakery

**Comment by rabernat** [comment]
I created a category on the Discourse forum for Pangeo Forge: https://discourse.pangeo.io/c/working-groups/pangeo-forge/62

We will post updates about the bi-weekly meetings on this thread: https://discourse.pangeo.io/t/pangeo-forge-working-group-and-coordination-meetings/2816/2
