### ISSUE TITLE
Frontiers in Climate: Democratizing Data - Paper Revisions

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/roadmap#38]
We are still waiting for the reviews to come in from Frontiers.

In the meantime, noting so I don't forget that @koldunovn saw our [preprint](https://eartharxiv.org/repository/view/2726/) and helpfully pointed out that I'd used the wrong citation for the FESOM model. The output we have ingested into Pangeo Forge is in fact, FESOM2, for which the correct citation, per Nikolay, is 

> Danilov, S., Sidorenko, D., Wang, Q., and Jung, T.: The Finite-volumE Sea ice–Ocean Model (FESOM2), Geosci. Model Dev., 10, 765–789, https://doi.org/10.5194/gmd-10-765-2017, 2017.

I've just corrected this in Overleaf: https://www.overleaf.com/project/6103c3cb2cc6aad53b3bf81d

When the reviews land, I'll ping all of the paper co-authors here; but sparing everyone the @ for now.

**Comment by cisaacstern** [comment]
Note to all co-authors: the editor has granted us an extension. Our review responses are now due three weeks from today, on Tuesday November 9.

**Comment by cisaacstern** [comment]
👋 Paper team, I've now made Track Changes edits to [our Overleaf](https://www.overleaf.com/project/6103c3cb2cc6aad53b3bf81d) which I believe address all of the review points enumerated in [this Google Doc](https://docs.google.com/document/d/1tqI-G9gjLMLoCLND5LkyxCNZG0rgN1GC8DV-ZmcUj_I/edit#heading=h.3aaxpfqm0ja7).

This is due **this upcoming Tuesday, November 9**. Sometime before Tuesday, I would appreciate if you could read through the document, and make any final edits (grammatical, content, etc.) using Track Changes. I will then do a final read-through and submission of our revised manuscript on Tuesday.

Thanks!

**Comment by alxmrs** [comment]
A few points of feedback on my last read through the paper: 
* I was confused about what "FAIR" data referred to. 
* I think the `fsspec-reference-maker` project was renamed to `Kerchunk`, though the former still appears in PyPi. I'm not sure what the most appropriate name would be – it's worth reviewing.

**Comment by rabernat** [comment]
I have reviewed the paper and response document. I have added a few minor suggestions. It looks great! Excellent job on managing the whole process Charles!

You have my ✅  to submit whenever you're ready.

**Comment by alxmrs** [comment]
* Line 276 reads `parrelizable`, it should be `parallelizable`.
* Line 540: `are be` --> This sentence confuses me, is this a mistake? 
* In general, there is inconsistent capitalization for subsections.

**Comment by rabernat** [comment]
Alex--given the tight timeline, the best thing you could do at this point would be to make the changes yourself.

**Comment by chiaral** [comment]
I made one minor edit:
- line 325 used to be "Pangeo Forge's initial algorithms produce of Zarr" - I took "of" out

looks great - I think it is also very "approachable" for users. I couldn't follow the more data engineering part, but I appreciated the clear explanation of the steps involved in the process, how some are meant to read only metadata and prepare the target, and when the actual heavy lifting happens. It also helps people like me - probably a typical user - to learn some important technical language and learn more about data engineering/cataloging  challenges.

**Comment by alxmrs** [comment]
> Alex--given the tight timeline, the best thing you could do at this point would be to make the changes yourself.

Sorry about that -- I didn't think I had overleaf access (I do).

**Comment by cisaacstern** [comment]
I've just submitted our revised manuscript. Thanks to all for your generous and helpful contributions.

<img width="439" alt="success" src="https://user-images.githubusercontent.com/62192187/141015646-c256dc8b-4fdb-4dcc-b658-635be78b7571.png">

**Comment by cisaacstern** [comment]
"I am pleased to inform you that your manuscript 'Pangeo Forge: Crowdsourcing Analysis-Ready, Cloud Optimized Data Production' has been approved for production and accepted for publication in Frontiers in Climate, section Climate Services.
Proofs are being prepared for you to verify before publication." 

😁 Great work everyone!

**Comment by jhamman** [comment]
Nice work all, especially @cisaacstern!

**Comment by alxmrs** [comment]
Congratulations, all!

One minor issue: My last name is misspelled in the accepted manuscript. How can I get this changed? 

The email reads "Melrose" when it should read `Merose`.

**Comment by cisaacstern** [comment]
@alxmrs, yes I noticed that.

I'll correct it when Frontiers sends the proofs, along with any other typos (I'm know of at least one other).
