### ISSUE TITLE
Managing pangeo-forge infrastructure

### ISSUE THREAD

**Issue by jhamman** [pangeo-forge/roadmap#4]
Pangeo Forge will require a bit of infrastructure that will need to be strategically managed. Namely:

1. Prefect agents
1. Cloud object stores
1. Web components (dashboard, catalog, etc.)

(1) and (2) are likely to be distributed across multiple clouds/regions and would benefit from some degree of central management and/or tracking. Let's use this roadmap issue to brainstorm how this infrastructure should be managed.

**Comment by TomAugspurger** [comment]
For reference, https://github.com/pangeo-forge/terraclimate-feedstock/issues/3#issuecomment-685941150 has a hopefully complete log of the manual steps for getting stuff set up (assuming you already have a kubernetes cluster).

I'm not wild about introducing more technology here, but if we're trying to manage multiple deployments across multiple clouds, using terraform may be the way to go.

**Comment by jhamman** [comment]
This issue is very stale. Closing now.
