### ISSUE TITLE
Frontiers in Climate 2nd (and last? 🤞 ) Proof

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/roadmap#45]
Our second (and hopefully last) Authors Proof is ready for review. I've uploaded it as `Authors_Proof_2.pdf` to [our Overleaf project](https://www.overleaf.com/project/6103c3cb2cc6aad53b3bf81d). Upon first skim, it looks like the issues identified in #43 have all been addressed. Please take a look and let me know if you see anything that needs changing (I spy one or two nits, e.g. linked figure name is not resolved properly in caption to Listing 3).

The journal changed our **Conflict of Interest** statement from

> The  authors  declare  that  the  research  was  conducted  in  the  absence  of  any  commercial or financial relationships that could be construed as a potential conflict of interest.

to

> AM was employed by company Google. SH was employed by company Development Seed.
>
> The remaining authors declare that the research was conducted in the absence of any commercial or financial relationships that could be construed as a potential conflict of interest.

Don't know if we'd prefer this phrased differently, so thought I'd bring our attention to it. I'll plan to incorporate any corrections others share with me into a response for the journal to be sent out a week from today on Friday February 21.

cc @rabernat @jhamman @rwegener2 @chiaral @sharkinsspatial @alxmrs

**Comment by alxmrs** [comment]
It looks like my name was not added to this overleaf version. I've just added it back. 

Re: conflict-of-interest: Looks good to me.

**Comment by alxmrs** [comment]
Also: I checked the view of the paper in the journal the other day – it looks like my name has not been updated on their side somehow.

**Comment by cisaacstern** [comment]
> It looks like my name was not added to this overleaf version. I've just added it back.

I believe you are referring to the `.tex` on Overleaf. At this point, we are working purely from the `Authors_Proof_2.pdf`, on which your name is present and (phew) spelled correctly.

> Re: conflict-of-interest: Looks good to me.

👍 

> Also: I checked the view of the paper in the journal the other day – it looks like my name has not been updated on their side somehow.

I'll make sure that the changes reflected in `Authors_Proof_2.pdf` propagate through other versions on Frontiers.

**Comment by jhamman** [comment]
👍 on the revised conflict of interest.

**Comment by rwegener2** [comment]
One typo I noticed while re-reading: on page 13 line 1425 the line states "Zarr are idea for powering APIs".  I think we mean "Zarr are idea**l** for powering APIs"

👍🏻 re: the revised conflict of interest.

**Comment by cisaacstern** [comment]
Just realized page 12 line 1322 says that we aim to publicly launch (i.e. have a deployed Columbia bakery) in "December 2021". I'll revise that to reflect the updated timeline.

**Comment by cisaacstern** [comment]
I've have submitted this Proof with the corrections discussed above. They were all quite minor, so I have not requested an additional Proof prior to publication. I expect the next notification I provide this group will be of the successful publication of our paper. Thank you all again for your contributions.

(@alxmrs, I'm aware that there is a lingering question of your name's misspelling on the journal's web interface. As noted above, this issue was not present on the PDF Proof itself. If it persists as a problem on the web interface post-publication, I will follow up with the journal.)

**Comment by alxmrs** [comment]
Thanks Charles!

**Comment by cisaacstern** [comment]
> I expect the next notification I provide this group will be of the successful publication of our paper. 

🎉 http://links.email.frontiersin.org/ls/click?upn=Dpg5ochww630xh6EMvshS4k2vZe-2Fd8MH-2FVpzt1-2FUQD91C-2FNL5bIclwWnNjv5HD9iQlI2aWVL1jOX1OW7eJBy-2F-2B9jgSFPb4rwuQN3-2B9RkC6rL7ENDuNouFpats7U-2FV8wFYW8PkB0hFMyR-2BQS4gXJw4BfljDYRBjGXOBJbXJWZ0Xxfs88jggsIqVWYlNr-2Fsxg9e9zcBglcr6ajMuyPBy03C03LGtg3en7yAD80-2F1QZflUTElImF-2FJT06C8nOU6ke2h8Qdqs-2BXmXQJuV4q6oIEnncMKr-2BROYLwNOmT4mAypxZ33FjK3C0AiOT3LEM9ovlhvBOEK_bF2uHWnL-2B7pWEYhWivHR2kU7Ehwv6-2BDprfpwhk3D7JiIINZUc-2BvClOb2pDoMw8fg64-2BqCvoMyPPWS0dDBkYGJf5nzGcdfvgoRjGBfLa5yXHYdycXoKl5N-2FAhH0wilxUKCCRNe8n0ryiGPXcPnxLRhUwSgVAHOBo5ig9NXlFt6Fu-2BINORliXHburnzHS0Okc9Nh0IIfkCF0e8ClWBHScs9mf0FH6r5TRnkZnvL2sZaHYUeSU5CWFviiiXypBnw2LdmnsKWgrGXw1brup39FQKMA-3D-3D

**Comment by jhamman** [comment]
Amazing! Thanks for the hard work here @cisaacstern!
