### ISSUE TITLE
SciPy Talk Proposal (Deadline Feb. 11)

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/roadmap#46]
[SciPy 2022](https://www.scipy2022.scipy.org/talk-poster-presentations) has a "Data Life Cycle" track

> Data handling is the common thread that ties together scientific applications in SciPy. This is true across academia, industry, and government where each brings a unique perspective to this challenge. While we talk a lot about what we do with data, we don’t always talk about how we work with the data. This track is dedicated to the life cycle of data. This includes anything from data engineering tools for collection, storage, to pipelines for creating analysis-ready data. Topics may include reproducibility, open science and reproducible research, persistence, stewardship, data management systems, continuity and maintenance of legacy code, and principles of software engineering effectiveness

I plan to submit a talk proposal about Pangeo Forge. Will post my proposal here for feedback from the team.

**Comment by jhamman** [comment]
This was accepted and delivered: https://www.youtube.com/watch?v=sY20UpYCAEE
