### ISSUE TITLE
pangeo-forge for rechunking?

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-forge/roadmap#54]
I didn't see any recipes that use rechunking and I think I remember @rabernat saying pangeo-forge does not do rechunking yet.    And I didn't find any reference here in the roadmap (it might be just me not searching correctly of course). 

So I guess I'm wondering:
* Is it correct that pangeo-forge does not yet support rechunking?
* If it doesn't, is there a plan to support it? 
* If there is a plan to support it, what would the time scale likely be?

**Comment by cisaacstern** [comment]
Thanks for raising this question @rsignell-usgs.

Pangeo Forge Recipes does support rechunking via the target_chunks keyword argument on XarrayZarrRecipe.

I would venture that at somewhere around half of recipes I've seen (if not more) make use of this feature.

The forthcoming refactor of Pangeo Forge Recipes will also support rechunking via the same keyword argument.

**Comment by rabernat** [comment]
So the latest version, unreleased but available on the `beam-refactor` branch, certainly supports rechunking in a fairly robust and general way. You can basically specify what you want your target chunks to be, and it will figure out how to make it happen.

It also supports the ability to have the inputs be zarr data.

What is not well tested, but may work, is Zarr to Zarr rechunking, a la Rechunker. I'm not sure what would happen if you created a recipe with just one huge zarr dataset as input. But it would be a useful thing to try.

**Comment by rsignell-usgs** [comment]
Okay, thanks @cisaacstern and @rabernat for clarifying the situation.   Hopefully I can be helpful in this regard -- we would like to rechunk the National Water Model  streamflow dataset on AWS public dataset program into different chunk shapes -- basically data rods to facilitate time series extraction.   
``` 
aws s3 ls --no-sign-request s3://noaa-nwm-retrospective-2-1-zarr-pds/
```

**Comment by rabernat** [comment]
Is there a reason you're not using rechunker for this?

**Comment by rsignell-usgs** [comment]
The data is already all on AWS Public Data, and rechunking using kubernetes (Dask gateway) on AWS seems to be slow, I think because we are writing/reading the very small objects from the temp zarr to s3.   So I was looking for a different solution to rechunking.   We can also try running rechunker on AWS Parallel Cluster where the workers could see fast SSD drives.   Perhaps I should raise this as item on rechunker discussions?

**Comment by alxmrs** [comment]
I think https://github.com/google/xarray-beam may be really useful here, check out this example: 
https://github.com/google/xarray-beam/blob/main/examples/era5_rechunk.py

It should be deployable on AWS via Flink or Spark.
